services:
  db:
    image: postgres:17
    container_name: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: api
    depends_on:
      - db
    environment:
      POSTGRES_URI: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    ports:
      - "8080:8080"
    command: ["api"]

  migrations:
    build: .
    container_name: migrations
    depends_on:
      - db
    environment:
      POSTGRES_URI: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    entrypoint: ["/bin/sh", "-c", "./scripts/migration-up"]
    restart: "no"

volumes:
  pgdata:
