// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/1755/bookstore-api/api/routers/health"
)

// Injectors from wire.go:

func InjectApplication(configPath ConfigPath) (*Application, func(), error) {
	config, err := NewConfig(configPath)
	if err != nil {
		return nil, nil, err
	}
	serverConfig := config.Server
	routerBuilder := health.NewRouterBuilder()
	server := NewServer(serverConfig, routerBuilder)
	application := NewApplication(configPath, server)
	return application, func() {
	}, nil
}
