name: CI

on:
  push:
    branches:
      - "*"

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.23" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Check formatting
        run: |
          go fmt ./...
          if [[ -n "$(git status --porcelain)" ]]; then
            git --no-pager diff
            exit 1
          fi

      - name: Check code generation
        run: |
          go generate ./...
          if [[ -n "$(git status --porcelain)" ]]; then
            git --no-pager diff
            exit 1
          fi

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62
          args: --timeout=3m
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run tests
        run: go test -v -race -p 4 ./...
